name: CIGH Scraping

on:
  schedule:
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      # Use the Posit binary manager for lightning-fast installs
      RSPM: "https://packagemanager.posit.co/cran/__linux__/jammy/latest"
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'
          use-public-rspm: true

      # This step automatically identifies and installs 
      # both system dependencies (libuv, libcurl, etc.) and R packages
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::googlesheets4

      - name: Scrape data
        run: R -e 'source("cigh/cigh_preprocess.R", echo = TRUE)'

      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add kingcenter/*
          git commit --allow-empty -am "Updating data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: CIGH Project Mapper Error
          body: CIGH Project Mapper update failed. Please check the Google Sheet for errors.
          to: derekouyang@gmail.com
          from: City Systems